name: flutter_offline
description: A tidy utility to handle offline/online connectivity like a Boss.
version: 2.1.3
homepage: https://github.com/jogboms/flutter_offline

environment:
    sdk: '>=2.18.2 <3.0.0'
    flutter: '>=2.0.0'

dependencies:
    flutter:
        sdk: flutter
    connectivity_plus: ^4.0.1
    network_info_plus: ^4.0.1
    internet_connection_checker: ^1.0.0+1
    async: ^2.9.0

dev_dependencies:
    flutter_lints: ^2.0.2
    flutter_test:
        sdk: flutter
