name: flutter_offline
description: A tidy utility to handle offline/online connectivity like a Boss.
version: 2.1.0
homepage: https://github.com/jogboms/flutter_offline

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.2.0
  network_info_plus: ^2.1.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
